server:
  http_port: ":8080"

database:
  master:
    host: "db"
    port: "5432"
    name: "warehouse_db"
    ssl_mode: "disable"

  slaves: [ ]

  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30m

jwt:
  ttl: "24h"